# Generated by Django 4.2.8 on 2023-12-13 13:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("store", "0003_variation"),
        ("carts", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="cartitem",
            name="variation",
            field=models.ManyToManyField(blank=True, to="store.variation"),
        ),
    ]
