# Generated by Django 4.2.8 on 2023-12-13 14:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("carts", "0002_cartitem_variation"),
    ]

    operations = [
        migrations.RenameField(
            model_name="cartitem", old_name="variation", new_name="variations",
        ),
    ]
